baseURL = "https://admiring-torvalds-b08d1f.netlify.app/"
languageCode = "en-us"
title = "CasCon 2021 census"
themesDir = "themes"
theme = "hyde"
author = "CasCon"
sectionPagesMenu = "main"

[params]
    themeColor = "theme-base-08"
    description = "Cascon census"