baseURL = "https://admiring-torvalds-b08d1f.netlify.app"
languageCode = "en-us"
title = "CasCon 2021 census"
themesDir = "themes"
theme = "hugo-theme-bootstrap"
author = "Tetizeraz"
sectionPagesMenu = "main"