baseURL = "https://heuristic-haibt-754dba.netlify.app/"
languageCode = "pt-br"
title = "Censo de 2021 do Discord do r/brasil"
themesDir = "themes"
theme = "hyde"
author = "r/brasil Discord"
sectionPagesMenu = "main"

[params]
    themeColor = "theme-base-08"
    description = "Censo do Discord 2021"